name: CD

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ROOT_PATH: MauiApp/
  CSPROJ_PATH: MauiApp/MauiApp.csproj
  ARTIFACTS_MACOS_PATH: artifacts_macos # RELATIVE TO github.workspace

jobs:
  macos-build-android-macos-ios:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'     

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --source https://api.nuget.org/v3/index.json

      # BUILD
      - name: Restore dependencies
        shell: pwsh
        run: |
          dotnet restore ${{ env.CSPROJ_PATH }}

      - name: Build MacCatalyst App
        shell: bash
        run: |
          dotnet build ${{ env.CSPROJ_PATH }} -f net6.0-maccatalyst -c Release
          dotnet publish ${{ env.CSPROJ_PATH }} -f net6.0-maccatalyst -c Release -p:BuildIpa=True  
     
      #POST-BUILD
      - name: Create artifacts folder
        shell: pwsh
        run: |
           cd ${{ github.workspace }}
           mkdir -p ${{ env.ARTIFACTS_MACOS_PATH }}

      - name: Copy MacOS package
        shell: pwsh
        run: |
           Get-Childitem –Path ${{ github.workspace }} -Include *.pkg -File -Recurse | Copy-Item -Destination ${{ env.ARTIFACTS_MACOS_PATH }}

      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:     
          name: "Podcast MacOS artifacts" 
          path: "${{ env.ARTIFACTS_MACOS_PATH }}/*"
          if-no-files-found: error
          retention-days: 90
